apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/service.yaml
images:
- name: PROJECT/IMAGE
  newName: ghcr.io/slikie/ping-pong
  newTag: 2bea51decdd19190bf36295ae5b450df3ddc1954
