apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-curd
  template:
    metadata:
      labels:
        app: project-curd
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: project-curd
          image: PROJECT/PROJECT-CURD
          volumeMounts:
          - name: shared-image
            mountPath: /app/images
